name: Build WF

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

  schedule:
    - cron: "10 14 * * 1-5" # At 14:10 on every day-of-week from Monday through Friday.

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Maven Build
        run: mvn install

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vprofile-app
          path: target/*.war

      - name: Notify Build Fails
        if: failure()
        run: echo "Build failed! Please check the logs."

  testing:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Maven Test
        if: github.ref == 'refs/heads/main'
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:check || true

      - name: Run test on other branches
        if: github.ref != 'refs/heads/main'
        run: echo "Tests are skipped on non-main branches."

  security-scan:
        needs: build
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v5
            with:
              fetch-depth: 0

          - name: Run Trivy Security Scan
            uses: aquasecurity/trivy-action@0.28.0
            with:
              scan-type: 'fs'
              scan-ref: '.'
              format: 'json'
              exit-code: '0'
              vuln-type: 'os,library'
              output: 'trivy-report.json'
          - name: Upload Trivy Scan Results
            uses: actions/upload-artifact@v4
            with:
              name: trivy-scan-results
              path: trivy-results.json