name: Build WF

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

<<<<<<< HEAD

  workflow_dispatch:

  schedule:
    - cron: '10 14 * * 1-5'  # At 14:10 on every day-of-week from Monday through Friday.   


  permissions:
    contents: read
=======
  workflow_dispatch:

  schedule:
    - cron: "10 14 * * 1-5" # At 14:10 on every day-of-week from Monday through Friday.


>>>>>>> 2872095da1a50053c83bed630b8dfdc2d8a64b63

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Maven Build
        run: mvn install

      - name: Upload Build Artifacts
       uses: actions/upload-artifact@v4
       with:
         name: vprofile-app
         path: target/*.war

      - name: Notify Build Fails
        if: failure()
        run: echo "Build failed! Please check the logs."

  testing:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Maven Test
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:check || true